namespace AdventOfCode2020.Puzzles
{
    internal static class Puzzle22Input
    {
        internal readonly static string[] Sample = new string[]
        {
            "Player 1:",
            "9",
            "2",
            "6",
            "3",
            "1",
            "",
            "Player 2:",
            "5",
            "8",
            "4",
            "7",
            "10",
        };

        internal readonly static string[] Input = new string[]
        {
            "Player 1:",
            "21",
            "22",
            "33",
            "29",
            "43",
            "35",
            "8",
            "30",
            "50",
            "44",
            "9",
            "42",
            "45",
            "16",
            "12",
            "4",
            "15",
            "27",
            "20",
            "31",
            "25",
            "47",
            "5",
            "24",
            "19",
            "",
            "Player 2:",
            "3",
            "40",
            "37",
            "14",
            "1",
            "13",
            "49",
            "41",
            "28",
            "48",
            "18",
            "7",
            "23",
            "38",
            "32",
            "34",
            "46",
            "39",
            "17",
            "2",
            "11",
            "6",
            "10",
            "36",
            "26",
        };
    }
}
